# git submodule to fetch for prebuilt toolchains
TOOLCHAIN_GIT_SUBMODULE=toolchains/gcc-linaro-5.1-2015.08-x86_64_arm-linux-gnueabihf

# host for autoconf
HOST=arm-linux-gnueabihf

# path to the sysroot
SYSROOT=toolchains/gcc-linaro-5.1-2015.08-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc

# git submodule to fetch u-boot from
UBOOT_GIT_SUBMODULE=boards/bcmadvancedresearch/ar6mxq/u-boot-imx

# u-boot config
UBOOT_CONFIG=ar6mx_defconfig

